services:
  - type: web
    name: corp-card-portal
    runtime: node
    plan: free
    nodeVersion: "20"
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: ORACLE_CONNECTION_STRING
        sync: false
      - key: ORACLE_USER
        sync: false
      - key: ORACLE_PASSWORD
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: UPSTASH_REDIS_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: NODE_ENV
        value: production
