services:
  - type: web
    name: corp-card-portal
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: ORACLE_CONNECTION_STRING
        sync: false
      - key: ORACLE_USER
        sync: false
      - key: ORACLE_PASSWORD
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: UPSTASH_REDIS_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: AUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: "https://corp-card-portal.onrender.com"
      - key: AUTH_URL
        value: "https://corp-card-portal.onrender.com"
      - key: CLOUDINARY_URL
        sync: false
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
